#pragma once
#include <glslstruct/value_types/base_type.hpp>
#include <glslstruct/value_types/value_type.hpp>
#include <glslstruct/value_types/ValueType.hpp>
#include <glslstruct/value_types/scalar_type.hpp>
#include <glslstruct/value_types/vec_type.hpp>
#include <glslstruct/value_types/mat_type.hpp>
#include <glslstruct/value_types/struct_type.hpp>
#include <glslstruct/value_types/array_type.hpp>